


                                                             每 个 格 子 1 word (32 个 字 节 )
+------+-----+------+------+------+------+-------+--------+------+------+------+-------+------+------+------+------+
|      |     |      |      |      |      |       |        |      |      |      |       |      |      |      |      |
|      |     |      |      |      |      |       |        |      |      |      |       |      |      |      |      |
+------------------------------------------------------------------------------------------------------------------+
|      |     |      |      |      |      |       |        |      |      |      |       |      |      |      |      |
|      |     |      |      |      |      |       |        |      |      |      |       |      |      |      |      |
+------------------------------------------------------------------------------------------------------------------+
|      |     |      |      |      |      |       |        |      |      |      |       |      |      |      |      |
|      |     |      |      |      |      |       |        |      |      |      |       |      |      |      |      |
+------------------------------------------------------------------------------------------------------------------+
|      |     |      |      |      |      |       |        |      |      |      |       |      |      | 1000 |length|
|      |     |      |      |      |      |       |        |      |      |      |       |      |      | 0000 |      |
+------+-----+------+------+------+------+-------+--------+------+------+------+-------+------+------+------+------+
                                                                                                    448           512




+------+-----+------+------+                        F(X,Y,Z)=(X&Y)|((~X)&Z)
|  A   |  B  |  C   |  D   |                        G(X,Y,Z)=(X&Z)|(Y&(~Z))
|      |     |      |      |                        H(X,Y,Z)=X^Y^Z
+------+-----+------+------+                        I(X,Y,Z)=Yv(X|(~Z))
  01     89     fe     76
  23     ab     dc     54                           FF(a,b,c,d,Mj,s,ti) a=b+((a+F(b,c,d)+Mj+ti)<^<s) ： 换 abcd 顺 序 计 算 16次
  45     cd     ba     32                           GG(a,b,c,d,Mj,s,ti) a=b|((a|G(b,c,d)|Mj|ti)<->s) ： 换 abcd 顺 序 计 算 16次
  67     ef     98     10                           HH(a,b,c,d,Mj,s,ti) a=b|((a|H(b,c,d)|Mj|ti)<->s) ： 换 abcd 顺 序 计 算 16次
                                                    II(a,b,c,d,Mj,s,ti) a=b+((a+I(b,c,d)+Mj+ti)<v<s) ： 换 abcd 顺 序 计 算 16次
                                                                                                     共 计 算 64次