scheme: Gemini
darkmode: true
menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
avatar:
  # Replace the default image and set the url here.
  url: https://avatars.githubusercontent.com/u/1488942?s=400&v=4
  # If true, the avatar will be displayed in circle.
  rounded: true
  # If true, the avatar will be rotated with the cursor.
  rotated: false
social:
  GitHub: https://github.com/rickgit || fab fa-github
  E-Mail: mailto:anshu.wang@qq.com || fa fa-envelope
codeblock:
  # Code Highlight theme
  # All available themes: https://theme-next.js.org/highlight/
  theme:
    light: a11y-light
    dark: a11y-dark
# `Follow me on GitHub` banner in the top-right corner.
github_banner:
  enable: true
  permalink: https://github.com/rickgit
