@startgantt
' printscale weekly
saturday are closed
sunday are closed
Project starts the 2020/03/12
[男女生引导] lasts 2 days
-- 第二周 --
then [首页-推荐，男生，女生]   starts  2020/03/16 
[首页-推荐，男生，女生] lasts 2 days
then [首页-分类-排行榜移到书城] starts  2020/03/18
then [首页-书城调整界面（推荐页面轮播图，主编推荐，猜你喜欢，男生轮播图）和排行榜UI] starts  2020/03/19
then [书城点击事件，添加推荐ui更多点击事件，男生模块更多箭头，分类UI] starts  2020/03/20
-- 第三周 --
then [搜索界面有问题，缺热门搜索接口；无结果界面；排行榜（人气有问题）] starts  2020/03/23
then [分类，书籍详情] starts  2020/03/24
then [福利 70%] starts  2020/03/25
then [书籍详情页 30%] starts  2020/03/26
then [福利对话框，书籍内容页 ，书籍阅读页] starts  2020/03/27
-- 第四周 --
then [书籍阅读页，书城网页异常，对话框，底部菜单没有截图和状态，没有右上角菜单的按钮，AppBarLayout无法盖住] starts 2020/03/30
then [书籍阅读页底部结构修改，阅读页没有设计按钮] starts 2020/03/31
then [书籍阅读页底部结构修改，！排序没有切图，代码审核-提交代码] starts 2020/04/01
then [书籍阅读页切图] starts 2020/04/02
then [书籍阅读页切图] starts 2020/04/03

-- 第五周 --
then [调节接口] starts 2020/04/07
then [书城精选-女生最爱，出版-xx最爱（未找到）；] starts 2020/04/07
then [书城精选-女生最爱，出版-xx最爱（未找到）；] starts 2020/04/08
then [搜索数量限制；对话框全面屏高度设置；] starts 2020/04/09
then [封板；搜索限制行数；夜间模式兼容旧版本；review代码] starts 2020/04/10
-- 第六周 --
then [修改开屏；福利自动跳动；部分样式] starts 2020/04/13
then [修改bug（1.开屏；2.书城推荐banner，搜索）] starts 2020/04/14
then [修改bug（书籍详情界面模糊处理，首页界面标题高度调整，及部分界面微调）] starts 2020/04/15
then [修改bug（环境出问题；阅读页面）] starts 2020/04/16
then [修改bug（调整UI），tapd问题] starts 2020/04/17

-- 第七周 --
then [修改bug（批量打包，调整UI）] starts 2020/04/20
then [增加书城接口，调整阅读界面] starts 2020/04/21
then [批量打包，标题修改，提交发布稳定包] starts 2020/04/21

@endgantt